apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pv-claim
  namespace: exam-budis-upload
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
