apiVersion: v1
kind: Service
metadata:
  name: hello-app
  namespace: exam-budis-upload
spec:
  selector:
    app: hello-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082 
