apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: template-pv-claim
  namespace: exam-budis-template
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
